#This is a python project
language: python
#This project requires Python 3.5
python:
 - 3.5
#How to run tests
install:
 - pip install nosetests
 - pip install coverage
script: make

#coveralls
after_success:
  - coveralls
